version: '3.9'
services:
    dokeboard:
        image: node:alpine
        container_name: linkheap
        entrypoint: /bin/sh
        ports:
            - 8000:8000
        working_dir: /srv/linkheap
        volumes:
            - type: bind
              source: ./
              target: /srv/linkheap
        tty: true
